### ISSUE TITLE
Add CHANGELOG

### ISSUE THREAD

**Issue by SeanTAllen** [ponylang/changelog-tool#16]
The changelog-tool needs its own CHANGELOG!

Along with this, we should work with @jemc to get automatic changelog updates working on this repo including adding the appropriate labels.

**Comment by Theodus** [comment]
It's starting to get meta!

**Comment by SeanTAllen** [comment]
The best 4 letter word.

**Comment by Theodus** [comment]
![](https://i.imgflip.com/1w03hw.jpg)
