### ISSUE TITLE
Add "new" command

### ISSUE THREAD

**Issue by SeanTAllen** [ponylang/changelog-tool#30]
To make using the CHANGELOG tool easier. It would be good if there was a "new" command that would create an initial, empty, valid, changelog.

**Comment by Theodus** [comment]
This should also include an argument for the project name rather than "Pony compiler and standard library"

**Comment by SeanTAllen** [comment]
Or just a generic "this project" seems fine

**Comment by SeanTAllen** [comment]
Actually generic seems best. fewer options. human can update if they want.

**Comment by Theodus** [comment]
Closed by #32
