### ISSUE TITLE
Add "Add" command

### ISSUE THREAD

**Issue by SeanTAllen** [ponylang/changelog-tool#34]
There is currently no way to use the changelog-tool to add a new changelog entry.

The add command should take:

- the section to update (added, fixed, changed)
- entry text

and then update the appropriate section by adding the new entry at the end of the section.

Should accept the 

```
   -f, --file=CHANGELOG.md    Path of the changelog
   -e, --edit=false           Modify the changelog file
```

options that we use for other possible modifications command.

**Comment by Theodus** [comment]
Thanks again to @ordepdev for doing most of the heavy lifting on this one!
